title: web developer, coding tale
description: > 
  I'm a web developer, these days more of a gentleman programmer. 
  I work on a variety of projects and am interested in php frameworks, javascript libraries, 
  and cloud server hosting. I tend to follow technologies that allow you 
  to quickly build amazing things; mapping reached that inflection point a few years ago.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: jiwonob

# Author Settings
author: Jiwon Min # add your name
author-img: https://avatars3.githubusercontent.com/u/14918156 # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning. # add description
social-twitter: jiwonob
social-facebook: jiwonov
social-github: jiwonov
social-linkedin: jiwonov
social-email: jiwonov@gmail.com

# Disqus
discus-identifier: jiwonov

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
