# Site
name: "DESSIN"
title: "DESSIN"
description: "Time is an illusion. Lunchtime doubly so."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics:
disqus: 'jiwonov'
include: ["_pages"]
permalink: /:title/
email: jiwonov@gmail.com

# Authors
authors:
  min:
    name: Min
    display_name: Min
    avatar: 'assets/images/avatar.png'
    gravatar: a802ab0b02effbafa72236af61468490
    email: jiwonov@gmail.com
    web: https://log.dessin.dev
    twitter: https://twitter.com/mlniog
    description: "Opinions are potentially wrong, but definitely my own."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    gravatar: a802ab0b02effbafa72236af61468490
    email: jiwonov@gmail.com
    web: https://log.dessin.dev
    twitter: https://twitter.com/mlniog
    description: "Opinions are potentially wrong, but definitely my own."
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatar.png'
    gravatar: a802ab0b02effbafa72236af61468490
    email: jiwonov@gmail.com
    web: https://log.dessin.dev
    twitter: https://twitter.com/mlniog
    description: "Opinions are potentially wrong, but definitely my own."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page/:num
    
# Other
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client:
adsense-data-ad-slot:

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]