# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Dessin
email:       'jiwonov@gmail.com'
description: 'Those who are believed to be most abject and humble are usually most ambitious and envious.'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://dessin.dev' # The base hostname & protocol for your site
twitter:     'https://twitter.com/dnexxi'
github:      'https://github.com/dnessi'
instagram:   'https://www.instagram.com/dnexxi'
facebook:    'https://www.facebook.com/dnexxi'

markdown:      kramdown
permalink:     /:title
paginate:      10
paginate_path: /page/:num

sass:
  style: compressed

plugins:
  - jekyll-paginate

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename
